name: 'CircuitPython Memory Check'
description: 'Import a CircuitPython library and check the amount of RAM used'
outputs:
  import-names:
    description: 'The names of imports, as a JSON list'
    value: ${{ steps.find-imports.outputs.imports-found }}
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Checkout the repository
      uses: actions/checkout@v6
    - name: Build nativesim firmware
      uses: tekktrik/simulate-circuitpython-nativesim/build-firmware@main
      with:
        # TODO: Change this to use given or autodetected version
        version: 10.1.4
        firmware-filepath: ./firmware.exe
    - name: Upload firmware artifact
      uses: actions/upload-artifact@v7
      with:
        name: firmware.exe
        path: ./firmware.exe
    - name: Find imports
      id: find-imports
      shell: bash
      run: |
        IMPORTS_FOUND=$(python ${{ github.action_path }}/../scripts/find_imports.py)
        echo "imports-found=$IMPORTS_FOUND" >> "$GITHUB_OUTPUT"
