# SPDX-FileCopyrightText: 2026 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'CircuitPython Memory Check Preparation'
description: 'Build the firmware to analyze imported memory'
inputs:
  version:
    description: 'Version of CircuitPython to simulate'
    required: true
    default: main  # This should be "latest" eventually, and version autodetected
  circuitpython-folder:
    description: 'Folder name to use for the CircuitPython checkout'
    required: true
    default: 'cpysim'
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Setup system dependencies
      uses: tekktrik/simulate-circuitpython-nativesim/prepare-system@v2
    - name: Build nativesim firmware
      uses: tekktrik/simulate-circuitpython-nativesim/build-firmware@v2
      with:
        version: latest
        firmware-filepath: ./firmware.exe
    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v7
      with:
        name: firmware.exe
        path: ./firmware.exe
