# SPDX-FileCopyrightText: 2026 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'CircuitPython Memory Comparison'
description: 'Compare two different memory usage results'
inputs:
  results-filename:
    description: 'Filename for the results file should be written (as a JSON file)'
    required: true
    default: 'results.json'
  original-results-filename:
    description: 'Filename for the original results file should be written (as a JSON file)'
    required: true
    default: 'original_results.json'
  analysis-results-filename:
    description: 'Filename for the analysis text file will be written'
    required: true
    default: 'memory_analysis.txt'
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Download results artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.results-filename }}
        path: '.'
    - name: Download original results artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.original-results-filename }}
        path: '.'
    - name: Run analysis
      shell: bash
      run: |
        python ${{ github.action_path }}/../scripts/compare_memory.py \
        "${{ inputs.results-filename }}" \
        "${{ inputs.original-results-filename }}" \
        "${{ inputs.analysis-results-filename }}"
    - name: Upload analysis text as artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.analysis-results-filename }}
        path: ${{ inputs.analysis-results-filename }}
